title: andrea_settimi
logo: /01_img/snap_profile_img_reduced_round.png
description: I am a diplomed EPFL architect specialized on timber construction and digital fabrication. I am currently doing a PhD in augmented reality and carpentry at IBOIS (Laboratory for Timber Construction), at EPFL (Switzerland). I am interested in wearable devices and sensors that can help humans in performing better at work. Computer vision, point cloud processing, microprocessors and software development are among my topics of interest.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
